name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo 'Hello peeps from the pipeline!'

  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v3

      - name: Setup PSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: test_db
          postgresql user: mr_testerson
          postgresql password: pa55w0rd

      - name: Install dependencies
        run: npm install

      - name: Test app
        run: PGDATABASE=test_db PGUSER=mr_testerson PGPASSWORD=pa55w0rd npm run test
