name: Unit and Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo 'Hello everyone from the pipeline!'

  test-utils:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and Clone Repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Test utils
        run: npm run test-utils

  test-app:
    needs: test-utils
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and Clone Repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Setup Postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: test_db
          postgresql user: mr_testerson
          postgresql password: pa55w0rd

      - name: Test App
        run: PGDATABASE=test_db PGUSER=mr_testerson PGPASSWORD=pa55w0rd npm run test-app

  test-app-staging-db:
    needs: test-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and Clone Repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Test App
        run: NODE_ENV=production DB_URL=${{ secrets.DB_URL }} npm run test-app
